import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { ArrowLeft, Check, LogOut, Mail, RefreshCw, Search, Settings, X } from 'lucide-react';

type Enquiry = { id: string; full_name: string; email: string; mobile: string; service: string; message: string; status: string; email_status: string; email_sent_at: string | null; email_attempted_at: string | null; recipient_email: string | null; email_error: string | null; created_at: string };
type SettingsData = { recipient_email: string; business_email: string; business_phone: string; notify_admin: boolean };
const statuses = ['NEW', 'READ', 'IN_PROGRESS', 'RESPONDED', 'CLOSED'];
const panel = 'border border-white/10 bg-white/[0.035]';

async function api<T>(path: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(path, { ...options, credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...options.headers } });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'Request failed.');
  return data as T;
}

export default function AdminDashboard() {
  const [email, setEmail] = useState(''); const [authenticated, setAuthenticated] = useState(false); const [loginEmail, setLoginEmail] = useState(''); const [password, setPassword] = useState('');
  const [items, setItems] = useState<Enquiry[]>([]); const [counts, setCounts] = useState({ total: 0, new: 0, read: 0, responded: 0, failed: 0 });
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('ALL'); const [sort, setSort] = useState<'newest' | 'oldest'>('newest'); const [page, setPage] = useState(0);
  const [selected, setSelected] = useState<Enquiry | null>(null); const [tab, setTab] = useState<'enquiries' | 'settings'>('enquiries'); const [settings, setSettings] = useState<SettingsData>({ recipient_email: '', business_email: '', business_phone: '', notify_admin: true }); const [fallbackEmail, setFallbackEmail] = useState('');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState('');

  const load = useCallback(async () => {
    const result = await api<{ enquiries: Enquiry[]; counts: typeof counts }>('/api/admin/enquiries'); setItems(result.enquiries); setCounts(result.counts);
  }, []);
  const loadSettings = useCallback(async () => { const result = await api<{ settings: SettingsData; fallbackEmail: string }>('/api/admin/settings'); setSettings(result.settings); setFallbackEmail(result.fallbackEmail); }, []);
  useEffect(() => { api<{ email: string }>('/api/admin/session').then((result) => { setAuthenticated(true); setEmail(result.email); }).catch(() => {}); }, []);
  useEffect(() => { if (authenticated) { load().catch((e) => setError(e.message)); loadSettings().catch((e) => setError(e.message)); } }, [authenticated, load, loadSettings]);

  const visible = useMemo(() => items.filter((item) => (filter === 'ALL' || item.status === filter || (filter === 'FAILED' && item.email_status === 'FAILED')) && `${item.full_name} ${item.email} ${item.mobile} ${item.service} ${item.message}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'newest' ? b.created_at.localeCompare(a.created_at) : a.created_at.localeCompare(b.created_at)), [items, filter, query, sort]);
  const pageSize = 10; const pageItems = visible.slice(page * pageSize, (page + 1) * pageSize);

  const signIn = async (event: FormEvent) => { event.preventDefault(); setError(''); setBusy(true); try { const result = await api<{ email: string }>('/api/admin/login', { method: 'POST', body: JSON.stringify({ email: loginEmail, password }) }); setEmail(result.email); setAuthenticated(true); setPassword(''); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const changeStatus = async (item: Enquiry, status: string) => { try { const result = await api<{ enquiry: Enquiry }>(`/api/admin/enquiries/${item.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); setItems((list) => list.map((row) => row.id === item.id ? result.enquiry : row)); setSelected(result.enquiry); await load(); } catch (e) { setError((e as Error).message); } };
  const retry = async (item: Enquiry) => { setBusy(true); setError(''); try { await api(`/api/admin/enquiries/${item.id}/retry`, { method: 'POST' }); await load(); setSelected((old) => old ? { ...old, email_status: 'SENT', email_error: null } : old); setSuccess('Email sent successfully.'); } catch (e) { setError((e as Error).message); await load(); } finally { setBusy(false); } };
  const saveSettings = async (event: FormEvent) => { event.preventDefault(); setError(''); setBusy(true); try { await api('/api/admin/settings', { method: 'PUT', body: JSON.stringify(settings) }); setSuccess('Settings saved.'); await loadSettings(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const logout = async () => { await api('/api/admin/logout', { method: 'POST' }).catch(() => {}); setAuthenticated(false); setEmail(''); };

  if (!authenticated) return <main className="flex min-h-screen items-center justify-center bg-black px-5 text-white"><form onSubmit={signIn} className={`${panel} w-full max-w-md p-7 sm:p-9`}><a href="/" className="mb-10 inline-flex items-center gap-2 text-[10px] uppercase tracking-[0.2em] text-white/50 hover:text-brand"><ArrowLeft className="h-4 w-4" /> Fourza Media</a><p className="section-kicker">Secure access</p><h1 className="section-title mt-5 text-5xl">Admin <span className="text-brand">login.</span></h1><div className="mt-8 grid gap-4"><label className="grid gap-2 text-[10px] uppercase tracking-[0.16em] text-white/50">Email<input required type="email" autoComplete="username" value={loginEmail} onChange={(e) => setLoginEmail(e.target.value)} className="border border-white/15 bg-black px-4 py-3 text-sm normal-case tracking-normal text-white outline-none focus:border-brand" /></label><label className="grid gap-2 text-[10px] uppercase tracking-[0.16em] text-white/50">Password<input required type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} className="border border-white/15 bg-black px-4 py-3 text-sm normal-case tracking-normal text-white outline-none focus:border-brand" /></label>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}<button disabled={busy} className="bg-brand px-5 py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-black disabled:opacity-50">{busy ? 'Signing inâ€¦' : 'Sign in'}</button></div></form></main>;

  return <main className="min-h-screen bg-[#080808] text-white"><header className="border-b border-white/10 bg-black px-5 py-5 sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><a href="/" className="font-display text-lg font-bold uppercase tracking-[0.08em]">Fourza <span className="text-brand">Media</span><span className="ml-3 text-[9px] font-normal tracking-[0.2em] text-white/35">ADMIN</span></a><div className="flex items-center gap-4"><span className="hidden text-xs text-white/50 sm:inline">{email}</span><button onClick={logout} className="inline-flex items-center gap-2 text-[9px] uppercase tracking-[0.17em] text-white/55 hover:text-brand"><LogOut className="h-4 w-4" /> Log out</button></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-10 sm:px-8 lg:px-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="section-kicker">Fourza Media / Workspace</p><h1 className="section-title mt-4 text-5xl sm:text-6xl">Enquiries<span className="text-brand">.</span></h1></div><div className="flex gap-2"><button onClick={() => setTab('enquiries')} className={`inline-flex items-center gap-2 border px-4 py-3 text-[9px] uppercase tracking-[0.16em] ${tab === 'enquiries' ? 'border-brand bg-brand text-black' : 'border-white/15 text-white/55'}`}><Mail className="h-4 w-4" /> Enquiries</button><button onClick={() => setTab('settings')} className={`inline-flex items-center gap-2 border px-4 py-3 text-[9px] uppercase tracking-[0.16em] ${tab === 'settings' ? 'border-brand bg-brand text-black' : 'border-white/15 text-white/55'}`}><Settings className="h-4 w-4" /> Settings</button></div></div>
      {(error || success) && <div className={`mb-5 flex items-center justify-between border px-4 py-3 text-sm ${error ? 'border-red-400/30 text-red-200' : 'border-brand/30 text-white/75'}`}>{error || success}<button onClick={() => { setError(''); setSuccess(''); }} aria-label="Dismiss"><X className="h-4 w-4" /></button></div>}
      {tab === 'settings' ? <form onSubmit={saveSettings} className={`${panel} max-w-3xl p-5 sm:p-8`}><p className="section-kicker">Business settings</p><h2 className="mt-4 font-display text-3xl font-bold uppercase">Contact & delivery</h2><p className="mt-3 text-sm leading-6 text-white/45">SMTP settings are kept on the server in environment variables. The recipient below can be changed without exposing mail credentials.</p><label className="mt-7 grid gap-2 text-[10px] uppercase tracking-[0.16em] text-white/50">Enquiry recipient email<input type="email" value={settings.recipient_email || ''} onChange={(e) => setSettings({ ...settings, recipient_email: e.target.value })} placeholder={fallbackEmail || 'Uses ADMIN_EMAIL fallback'} className="border border-white/15 bg-black px-4 py-3 text-sm normal-case tracking-normal text-white outline-none focus:border-brand" /><span className="normal-case tracking-normal text-white/35">Leave blank to use server fallback{fallbackEmail ? `: ${fallbackEmail}` : '.'}</span></label><label className="mt-5 grid gap-2 text-[10px] uppercase tracking-[0.16em] text-white/50">Business contact email<input type="email" value={settings.business_email || ''} onChange={(e) => setSettings({ ...settings, business_email: e.target.value })} className="border border-white/15 bg-black px-4 py-3 text-sm normal-case tracking-normal text-white outline-none focus:border-brand" /></label><label className="mt-5 grid gap-2 text-[10px] uppercase tracking-[0.16em] text-white/50">Business phone number(s)<input value={settings.business_phone || ''} onChange={(e) => setSettings({ ...settings, business_phone: e.target.value })} className="border border-white/15 bg-black px-4 py-3 text-sm normal-case tracking-normal text-white outline-none focus:border-brand" /></label><button disabled={busy} className="mt-7 inline-flex items-center gap-2 bg-brand px-5 py-4 text-[10px] font-bold uppercase tracking-[0.17em] text-black disabled:opacity-50">Save Settings <Check className="h-4 w-4" /></button></form> : <>
        <div className="mb-7 grid grid-cols-2 gap-3 lg:grid-cols-5">{[['Total', counts.total], ['New', counts.new], ['Read', counts.read], ['Responded', counts.responded], ['Failed delivery', counts.failed]].map(([label, value]) => <div key={label} className={`${panel} p-4 sm:p-5`}><p className="text-[9px] uppercase tracking-[0.15em] text-white/40">{label}</p><p className="mt-3 font-display text-3xl font-bold">{value}</p></div>)}</div>
        <div className="mb-4 flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/35" /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(0); }} placeholder="Search name, email, phone, serviceâ€¦" className="w-full border border-white/12 bg-black/50 py-3 pl-10 pr-4 text-sm outline-none focus:border-brand" /></label><select value={filter} onChange={(e) => { setFilter(e.target.value); setPage(0); }} className="border border-white/12 bg-black px-4 py-3 text-xs"><option value="ALL">All enquiries</option>{statuses.map((status) => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}<option value="FAILED">Failed email</option></select><select value={sort} onChange={(e) => setSort(e.target.value as 'newest' | 'oldest')} className="border border-white/12 bg-black px-4 py-3 text-xs"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select><button onClick={() => load().catch((e) => setError(e.message))} className="border border-white/12 px-4 text-white/60 hover:border-brand hover:text-brand" aria-label="Refresh enquiries"><RefreshCw className="mx-auto h-4 w-4" /></button></div>
        <div className={`${panel} overflow-x-auto`}><table className="w-full min-w-[900px] border-collapse text-left"><thead className="bg-white/[0.025] text-[9px] uppercase tracking-[0.14em] text-white/40"><tr>{['Date', 'Name', 'Email', 'Mobile', 'Service', 'Message preview', 'Email', 'Status'].map((heading) => <th key={heading} className="border-b border-white/10 px-4 py-4 font-medium">{heading}</th>)}</tr></thead><tbody>{pageItems.map((item) => <tr key={item.id} onClick={() => setSelected(item)} className="cursor-pointer transition-colors hover:bg-white/[0.035]"><td className="whitespace-nowrap border-b border-white/5 px-4 py-4 text-[10px] text-white/50">{new Date(item.created_at).toLocaleDateString('en-IN')}</td><td className="border-b border-white/5 px-4 py-4 text-xs font-semibold">{item.full_name}</td><td className="border-b border-white/5 px-4 py-4 text-xs text-white/60">{item.email}</td><td className="border-b border-white/5 px-4 py-4 text-xs text-white/60">{item.mobile}</td><td className="border-b border-white/5 px-4 py-4 text-xs text-white/65">{item.service}</td><td className="max-w-52 border-b border-white/5 px-4 py-4 text-xs text-white/45">{item.message.slice(0, 70)}{item.message.length > 70 ? 'â€¦' : ''}</td><td className={`border-b border-white/5 px-4 py-4 text-[9px] uppercase tracking-[0.12em] ${item.email_status === 'SENT' ? 'text-emerald-300' : item.email_status === 'FAILED' ? 'text-red-300' : 'text-white/45'}`}>{item.email_status}</td><td className="border-b border-white/5 px-4 py-4 text-[9px] uppercase tracking-[0.1em] text-brand">{item.status.replace('_', ' ')}</td></tr>)}{pageItems.length === 0 && <tr><td colSpan={8} className="px-5 py-12 text-center text-sm text-white/40">No enquiries match your search.</td></tr>}</tbody></table></div>
        <div className="mt-4 flex items-center justify-between text-[10px] uppercase tracking-[0.14em] text-white/40"><span>{visible.length} enquiries</span><div className="flex items-center gap-3"><button disabled={page === 0} onClick={() => setPage((n) => n - 1)} className="border border-white/15 px-3 py-2 disabled:opacity-30">Previous</button><span>{page + 1} / {Math.max(1, Math.ceil(visible.length / pageSize))}</span><button disabled={(page + 1) * pageSize >= visible.length} onClick={() => setPage((n) => n + 1)} className="border border-white/15 px-3 py-2 disabled:opacity-30">Next</button></div></div>
      </>}
    </div>
    {selected && <div className="fixed inset-0 z-[80] flex justify-end bg-black/70 backdrop-blur-sm" onClick={() => setSelected(null)}><aside onClick={(e) => e.stopPropagation()} className="h-full w-full max-w-xl overflow-y-auto border-l border-white/10 bg-[#0c0c0c] p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="section-kicker">Enquiry details</p><h2 className="mt-4 font-display text-3xl font-bold uppercase">{selected.full_name}</h2></div><button onClick={() => setSelected(null)} className="border border-white/15 p-2 text-white/55 hover:text-brand" aria-label="Close details"><X className="h-4 w-4" /></button></div><dl className="mt-8 grid gap-5">{[['Email', selected.email], ['Mobile', selected.mobile], ['Service', selected.service], ['Submitted date', new Date(selected.created_at).toLocaleString('en-IN')], ['Email status', selected.email_status], ['Email attempted', selected.email_attempted_at ? new Date(selected.email_attempted_at).toLocaleString('en-IN') : 'Not attempted'], ['Recipient', selected.recipient_email || 'Not set']].map(([label, value]) => <div key={label}><dt className="text-[9px] uppercase tracking-[0.18em] text-white/35">{label}</dt><dd className="mt-1 break-words text-sm text-white/80">{value}</dd></div>)}<div><dt className="text-[9px] uppercase tracking-[0.18em] text-white/35">Message</dt><dd className="mt-2 whitespace-pre-wrap text-sm leading-7 text-white/75">{selected.message}</dd></div></dl>{selected.email_error && <p className="mt-5 border border-red-400/20 bg-red-400/5 p-3 text-xs text-red-200">{selected.email_error}</p>}<label className="mt-7 grid gap-2 text-[9px] uppercase tracking-[0.16em] text-white/40">Enquiry status<select value={selected.status} onChange={(e) => changeStatus(selected, e.target.value)} className="border border-white/15 bg-black px-4 py-3 text-xs text-white">{statuses.map((status) => <option key={status} value={status}>{status.replace('_', ' ')}</option>)}</select></label>{selected.email_status === 'FAILED' && <button disabled={busy} onClick={() => retry(selected)} className="mt-5 inline-flex w-full items-center justify-center gap-2 bg-brand px-5 py-4 text-[10px] font-bold uppercase tracking-[0.15em] text-black disabled:opacity-50"><RefreshCw className="h-4 w-4" /> Retry Email</button>}</aside></div>}
  </main>;
}
